### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by idirouhab** [friendsofgo/graphiql#4]
is there any plan to move it to Docker?

**Comment by joanlopez** [comment]
Hi @idirouhab,

We're planning to write an article about how to dockerise your Golang project for our recently published blog. Our idea is to dockerise (in parallel) our GQL repo.

Anyway, thanks a lot for your suggestion.

Cheers,
Joan

**Comment by joanlopez** [comment]
Hi @idirouhab,

Finally, this project was dockerized. Fixed at #5.
Docs still pending, we will upload it until the end of the day.

Do not hesitate to suggest us any other proposal!
Thanks a lot ;)

**Comment by idirouhab** [comment]
great @joanlopez
